openapi: "3.0.0"

info:
  version: "0.8.0a"
  title: GKCORE
  description: |
    API documentation of gkcore - GNUKhata's REST API server.

    **gkstatus codes:**
    The following is the meaning of the `gkstatus` codes, which are returned in `200` response:
    ```json 
      { 
      "Success": 0, 
      "DuplicateEntry": 1, 
      "UnauthorisedAccess": 2, 
      "ConnectionFailed": 3, 
      "BadPrivilege": 4, 
      "ActionDisallowed": 5, 
      "ProxyServerError": 6, 
      }
    ```
    **User roles:** These are the following user roles in an organisation with various access levels

    ```json
    {
      -1: "Admin",
      0: "Manager",
      1: "Operator",
      2: "Internal Auditor",
      3: "Godown In Charge",
    }
    ```

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: gktoken
    UserAuth:
      type: apiKey
      in: header
      name: gkusertoken

security:
  - ApiKeyAuth: []

paths:
  /:
    get:
      tags: ["Public API's"]
      summary: Check whether gkcore is running
      security: [{}]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  gkstatus:
                    type: integer
                    description: 0 - success, 1 - something else
                  version:
                    type: string
  /state:
    get:
      tags: ["Public API's", "State"]
      summary: Get list of state codes
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum: [all]
          required: true
      security: [{}]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  gkstatus:
                    type: integer
                  gkresult:
                    type: array
                    items:
                      type: object
                      properties:
                        state_code:
                          type: integer
                        state_name:
                          type: string
                        state_abbr:
                          type: string
  /log:
    $ref: "./logs/log.yaml"
  /log/dateRange:
    $ref: "./logs/dateRange.yaml"
  /export/json:
    $ref: "./data/export-json.yaml"
  /import/json:
    $ref: "./data/import-json.yaml"
  /export/xlsx:
    $ref: "./data/export-xlsx.yaml"
  /import/xlsx:
    $ref: "./data/import-xlsx.yaml"
  /accounts:
    $ref: "./accounts/index.yaml"
  /accounts/spreadsheet:
    $ref: "./accounts/spreadsheet.yaml"
  /closebooks:
    $ref: "./rollclose/closebooks.yaml"
  /rollover:
    $ref: "./rollclose/rollover.yaml"
