image: python:3.8-slim-buster
# include: "https://gitlab.com/gitlab-cd/ssh-template/raw/master/ssh.yml"

variables:
  POSTGRES_USER: "gkadmin"
  POSTGRES_PASSWORD: "gkadmin"
  POSTGRES_DB: "gkdata"
  GKCORE_DB_URL: "postgres://gkadmin:gkadmin@postgres:5432/gkdata"

# TODO add razorpay:ifsc image when related tests are added
services:
  - postgres:alpine

stages:
  - build
  - deploy

# build gkcore
gkcore_setup:
  stage: build
  script:
    - apt update && apt install -y build-essential libpq-dev
    - pip3 install -r requirements.txt
    - python3 setup.py develop
    - python3 initdb.py
    - pserve production.ini
    # run tests
    - python3 gkcore/tests/public_apis.py

# generate api docs
pages:
  script:
    - apt update && apt install -y build-essential libpq-dev
    - pip install -r requirements.txt
    - pip install pdoc
    - pdoc -o .pub/api-docs/ gkcore/
    - mv .pub public
    - ls public
    # - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
      - public

# run unit tests
# unit-tests:
#   stage: build
#   needs: ["setup"]
#   script:
#     - pip3 install requests
#     - python3 gkcore/tests/public_apis.py

# deploy devel branch changes to gkcore test server
update_test_server:
  stage: deploy
  script:
    - apt update && apt install -y curl
    - curl $TEST_SERVER_HOOK
  only:
    - devel
