# TODO
# - Fix tests
# - Fix failing deploy job
image: python:3.8-slim-buster
include: "https://gitlab.com/gitlab-cd/ssh-template/raw/master/ssh.yml"

variables:
  POSTGRES_USER: "gkadmin"
  POSTGRES_PASSWORD: "gkadmin"
  POSTGRES_DB: "gkdata"
  GKCORE_DB_URL: "postgres://gkadmin:gkadmin@postgres:5432/gkdata"

services:
  - postgres:alpine

stages:
  - build
  - test
  # - deploy

# build gkcore
gkcore-setup:
  stage: build
  script:
    - apt update && apt install -y build-essential libpq-dev
    - pip3 install -r requirements.txt
    - python3 setup.py develop
    - python3 initdb.py

# run tests
gkcore-tests:
  stage: test
  script:
    - pip3 install requests
    - python3 tests.py
# update the test server when devel branch is updated
# update-test-server:
#   stage: deploy
#   script:
#     - apt update && apt install -y ssh
#     # - mkdir /root/.ssh
#     # - echo $SSH_PRIV_KEY > /root/.ssh/id_ed25519
#     # - eval $(ssh-agent -s)
#     # - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
#     # - chmod 600 /root/.ssh/id_ed25519
#     # - ssh -T -o "StrictHostKeyChecking=no" $TEST_SERVER_ADDRESS /root/restart-gk.sh
#     - ssh_run "root" $TEST_SERVER_ADDRESS $SSH_PRIVATE_KEY /root/restart-gk.sh
#   only:
#     - devel
