# Docker compose file for gkcore local development

services:
  # Postgresql 12 image
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${GKCORE_DB_USER:-gkadmin}
      - POSTGRES_PASSWORD=${GKCORE_DB_PASSWORD:-gkadmin}
      - POSTGRES_DB=${GKCORE_DB_NAME:-gkdata}
    volumes:
      - gkdb:/var/lib/postgresql/data

  # REST API Server
  gkcore:
    restart: "always"
    image: digitalfreedom/gkcore:devel
    environment:
      - GKCORE_DB_HOST=${GKCORE_DB_HOST:-db}
      - GKCORE_DB_PORT=${GKCORE_DB_PORT:-5432}
      - PYRAMID_CONFIG_FILE=${PYRAMID_CONFIG_FILE:-production.ini}
    ports:
      - "6543:6543"
    depends_on:
      - db

volumes:
  gkdb:
