version: "3.3"
services:
  # postgresql 12 image
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=gkadmin
      - POSTGRES_PASSWORD=gkadmin
      - POSTGRES_DB=gkdata
    volumes:
      - gkdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # ifsc API server
  ifsc-server:
    image: razorpay/ifsc:latest
  # pgadmin to visualize postgres db
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gkcore.gk
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "3000:80"
  # gnukhata v7
  gkwebapp:
    image: digitalfreedom/gnukhata:v7.0update
    volumes:
      - gkdb_old:/var/lib/postgresql
    ports:
      - "6544:6544"

volumes:
  pgadmin:
  gkdb:
  gkdb_old:
